### ISSUE TITLE
Level doesn't end 关卡未完成

### ISSUE THREAD

**Issue by Daniamlnk** [nextisme/PvZ-hybrid-version#13]
I reached level 45, and when I killed all the zombies on the last wave, the level does not end. The game doesn't freeze, it just seems like the level isn't progressing. Although all plants are active, producing sun, etc. Restarting doesn't help.

我达到了45级，当我在最后一波杀死所有僵尸时，级别并没有结束。游戏并没有冻结，只是关卡似乎没有进展。尽管所有植物都很活跃，产生阳光等。重新启动没有帮助.

![Снимок экрана (25595)](https://github.com/user-attachments/assets/a7c480ee-6991-406b-b038-98e9be57882a)
![Снимок экрана (25592)](https://github.com/user-attachments/assets/3b0bcb92-2adf-48b1-8664-2a121b4f978c)

**Comment by L7132** [comment]
The author of this project is not the author of this game, and as a user, I don't know how to fix it. Maybe you should go to the video comment area [here](https://space.bilibili.com/97213827) to discuss, good luck!

**Comment by nighth3** [comment]
This bug was fixed in version 2.5.1
