### ISSUE TITLE
any chance of a english version?

### ISSUE THREAD

**Issue by Manka-Muakido** [nextisme/PvZ-hybrid-version#3]
i really loved this hybrid version/edition, but would be nice if it had a English versions

**Comment by qiuyueovo** [comment]
You can search on github, there is an English version, but I don't remember which address it is.

**Comment by qiuyueovo** [comment]
https://github.com/innovateplus/PVZHE-English

**Comment by qiuyueovo** [comment]
I haven't actually tried this version, so I don't know if there will be any problems.
