### ISSUE TITLE
v2.3

### ISSUE THREAD

**Issue by Maklith** [nextisme/PvZ-hybrid-version#5]
https://pan.quark.cn/s/549d16cf28e3#/list/share

**Comment by L7132** [comment]
[植物大战僵尸杂交版v2.3版本宣传片](https://www.bilibili.com/video/BV1Lb421J78C)
[植物大战僵尸杂交版v2.3.zip](https://pan.quark.cn/s/549d16cf28e3)
[窗口放大工具Magpie -v0.11.1](https://pan.quark.cn/s/5d62f89e3ca1)

**Comment by Maklith** [comment]
> [植物大战僵尸杂交版v2.3版本宣传片](https://www.bilibili.com/video/BV1Lb421J78C) [植物大战僵尸杂交版v2.3.zip](https://pan.quark.cn/s/549d16cf28e3) [窗口放大工具Magpie -v0.11.1](https://pan.quark.cn/s/5d62f89e3ca1)

?有没有可能只是告诉仓库作者该更新了

**Comment by nextisme** [comment]
收到

**Comment by nextisme** [comment]
在家里感觉没学校好玩
